### PR TITLE
EASY-1972: Implementeer easy-licenses als Maven artifact

### PR DESCRIPTION
**Pull request by vesaakerman**
Fixes EASY-1972

When applied it will
- make easy-licenses a `.jar `file (instead of .tar.gz)
- relocate licenses from `src/main/assembly/dist` into `src/main/resources`

@DANS-KNAW/easy

### CODE REVIEW

**Comment by rvanheest** [comment]
`bin.xml` should be removed as well, right?

**Comment by vesaakerman** [comment]
@rvanheest : yes indeed, probably `bin.xml` is not needed

**Comment by vesaakerman** [comment]
Could we delete the whole `assembly` directory?  Seems not to be necessary.

**Review by janvanmansum — COMMENTED** [review]
@vesaakerman : is the `version` file still used? The version number does not get filled in, so I guess not.

**Comment by vesaakerman** [comment]
The `version` file is indeed not used.  I see that e.g. in `easy-schema` the version is written into `target/version` directory.  How is the version used?  Should I include it also in easy-licenses?  Now that it is not included, I don't need to specify in the pom the `build/resources` tag.

**Comment by janvanmansum** [comment]
> The `version` file is indeed not used. I see that e.g. in `easy-schema` the version is written into `target/version` directory. How is the version used? Should I include it also in easy-licenses? Now that it is not included, I don't need to specify in the pom the `build/resources` tag.

In other modules  the `version` file is used so that the module can implement `some-module --version` and to print its version when the root servlet is called (if it is a service). I don't think it is needed here, as this is neither a command nor a service.

**Review by janvanmansum — CHANGES_REQUESTED** [review]
Also remove the exec-maven-plugin. It is configured to try and deploy to yum if `mvn deploy` is called, but there are no RPMs in this project to deploy.

**Pull request merged**
